In [2]:
#import Numpy librarry 

import numpy as np 

x= np.array([1,2,3])

#Output

print (x)

[1 2 3]


In [3]:
#numpy arange 

y = np.arange(10)
print (y)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
#lets create an array with shape [3,4]

a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 

#slicing array 

b = a[:2,1:3]
c = a[:2]



In [15]:
print (b)

[[2 3]
 [6 7]]


In [7]:
print (c)

[[1 2 3 4]
 [5 6 7 8]]
